backend:
  name: github
  repo: nrgouldBM/Bolstered-Media-Gatsby-Site
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: case-studies
    label: Case Studies
    folder: src/content/case-studies
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "case-study",
        }

  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: category, label: Category }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
