backend:
  name: github
  repo: nrgouldBM/Bolstered-Media-Gatsby-Site
  branch: main

media_folder: static/assets
public_folder: /assets

collections:
  - name: case-studies
    label: Case Studies
    folder: src/case-studies
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: category, label: Category }
      - { name: author, label: Author }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
